apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: o66ajoz7b-go 
  janus-idp.io/tekton: o66ajoz7b-go
  backstage.io/kubernetes-id: o66ajoz7b-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: o66ajoz7b-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml